name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v4.1.0
        with:
          config-file: cypress.config.ts
          record: false
          browser: chrome
          headless: true
      