name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          run: cypress open --config-file=cypress.config.ts
          config-file: cypress.config.ts
          record: false
          browser: chrome
          headless: true
      